services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.16
    environment:
      - DBA_PASSWORD=dba
    ports:
      - "8890:8890"
    volumes:
      - ./virtuoso/virtuoso.ini:/opt/virtuoso-opensource/database/virtuoso.ini
      - ./data/:/data/
    healthcheck:
      test: ["CMD-SHELL", "isql 1111 dba ${DBA_PASSWORD:-dba} exec='status();' >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  loader:
    image: openlink/virtuoso-opensource-7:7.2.16
    depends_on:
      virtuoso:
        condition: service_healthy
    volumes:
      - ./datasets:/datasets
      - ./data:/data
      - ./virtuoso/init.sh:/opt/scripts/init.sh
    entrypoint: ["bash","-lc","/opt/scripts/init.sh"]
    environment:
      DBA_PASSWORD: dba
      # DATASET_1: "/datasets/NYT.tar.gz|http://example.org/graph/nyt"           # 335197 triples
      # DATASET_2: "/datasets/LMDB.tar.gz|http://example.org/graph/lmdb"         # 6147996 triples
      # DATASET_3: "/datasets/Jamendo.tar.gz|http://example.org/graph/jamendo"   # 1049647 triples
      # DATASET_4: "/datasets/ChEBI.tar.gz|http://example.org/graph/chebi"       # 4772706 triples
      # DATASET_5: "/datasets/DrugBank.tar.gz|http://example.org/graph/drugbank" # 517023 triples
      # DATASET_6: "/datasets/GeoNames.tar.gz|http://example.org/graph/geonames" # 107950085 triples
      # DATASET_7: "/datasets/KEGG.tar.gz|http://example.org/graph/kegg"         # 1090830 triples
      # DATASET_8: "/datasets/SP2B.tar.gz|http://example.org/graph/sp2b"         # 10000457 triples
      # DATASET_9: "/datasets/SWDFood.tar.gz|http://example.org/graph/swdfood"   # 103595 triples

      DATASET_10: "/datasets/DBPedia-Subset.tar.gz|http://example.org/graph/dbpedia" # > 29 724 192 triples

    