events {}

http {
  server {
    listen 80 default_server;
    server_name 127.0.0.1 localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    ################################
    # SPARQL endpoints
    ################################
    

    location /sparql/chebi/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/chebi;
    }
    location /sparql/dbpedia/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/dbpedia;
    }
    location /sparql/drugbank/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/drugbank;
    }
    location /sparql/geonames/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/geonames;
    }
    location /sparql/jamendo/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/jamendo;
    }
    location /sparql/kegg/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/kegg;
    }
    location /sparql/lmdb/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/lmdb;
    }
    location /sparql/nyt/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/nyt;
    }
    location /sparql/sp2b/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/sp2b;
    }
    location /sparql/swdfood/ {
      proxy_pass http://virtuoso:8890/sparql;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/swdfood;
    }
    location /sparql/ {
      proxy_pass http://virtuoso:8890/sparql/;
      proxy_set_header X-SPARQL-Default-Graph http://localhost/sparql/sparql;
    }
  }
}
