events {}

http {
  proxy_read_timeout 1200s;

  server {
    listen 80 default_server;
    server_name 127.0.0.1 localhost;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    ################################
    # SPARQL endpoints
    ################################
    

    location /sparql/chebi {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/chebi&$args;
    }
    location /sparql/dbpedia {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/dbpedia&$args;
    }
    location /sparql/drugbank {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/drugbank&$args;
    }
    location /sparql/geonames {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/geonames&$args;
    }
    location /sparql/jamendo {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/jamendo&$args;
    }
    location /sparql/kegg {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/kegg&$args;
    }
    location /sparql/lmdb {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/lmdb&$args;
    }
    location /sparql/nyt {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/nyt&$args;
    }
    location /sparql/sp2b {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/sp2b&$args;
    }
    location /sparql/swdfood {
      proxy_pass http://virtuoso:8890/sparql?default-graph-uri=http://localhost/sparql/swdfood&$args;
    }
    location /sparql {
      proxy_pass http://virtuoso:8890/sparql;
    }
  }
}
